//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> ventaid { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<int> estadopagoid { get; set; }
    
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
