//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGV.Web.ServiceReferenceVentas {
    using System.Runtime.Serialization;
    using System;
    using System.ComponentModel.DataAnnotations;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad", Namespace="http://schemas.datacontract.org/2004/07/SGV.Services")]
    [System.SerializableAttribute()]
    public partial class Ciudad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentonombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamentonombre {
            get {
                return this.departamentonombreField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentonombreField, value) != true)) {
                    this.departamentonombreField = value;
                    this.RaisePropertyChanged("departamentonombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/SGV.Services")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ciudadidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadnombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechanacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ciudadid {
            get {
                return this.ciudadidField;
            }
            set {
                if ((this.ciudadidField.Equals(value) != true)) {
                    this.ciudadidField = value;
                    this.RaisePropertyChanged("ciudadid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ciudadnombre {
            get {
                return this.ciudadnombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadnombreField, value) != true)) {
                    this.ciudadnombreField = value;
                    this.RaisePropertyChanged("ciudadnombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fechanacimiento {
            get {
                return this.fechanacimientoField;
            }
            set {
                if ((this.fechanacimientoField.Equals(value) != true)) {
                    this.fechanacimientoField = value;
                    this.RaisePropertyChanged("fechanacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVentas.IServiceVentas")]
    public interface IServiceVentas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataCiudadesAll", ReplyAction="http://tempuri.org/IServiceVentas/GetDataCiudadesAllResponse")]
        SGV.Web.ServiceReferenceVentas.Ciudad[] GetDataCiudadesAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataCiudadesAll", ReplyAction="http://tempuri.org/IServiceVentas/GetDataCiudadesAllResponse")]
        System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Ciudad[]> GetDataCiudadesAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/CreatePersona", ReplyAction="http://tempuri.org/IServiceVentas/CreatePersonaResponse")]
        SGV.Web.ServiceReferenceVentas.Persona CreatePersona(SGV.Web.ServiceReferenceVentas.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/CreatePersona", ReplyAction="http://tempuri.org/IServiceVentas/CreatePersonaResponse")]
        System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> CreatePersonaAsync(SGV.Web.ServiceReferenceVentas.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/UpdatePersona", ReplyAction="http://tempuri.org/IServiceVentas/UpdatePersonaResponse")]
        SGV.Web.ServiceReferenceVentas.Persona UpdatePersona(SGV.Web.ServiceReferenceVentas.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/UpdatePersona", ReplyAction="http://tempuri.org/IServiceVentas/UpdatePersonaResponse")]
        System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> UpdatePersonaAsync(SGV.Web.ServiceReferenceVentas.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/DeletePersona", ReplyAction="http://tempuri.org/IServiceVentas/DeletePersonaResponse")]
        bool DeletePersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/DeletePersona", ReplyAction="http://tempuri.org/IServiceVentas/DeletePersonaResponse")]
        System.Threading.Tasks.Task<bool> DeletePersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataPersonasAll", ReplyAction="http://tempuri.org/IServiceVentas/GetDataPersonasAllResponse")]
        SGV.Web.ServiceReferenceVentas.Persona[] GetDataPersonasAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataPersonasAll", ReplyAction="http://tempuri.org/IServiceVentas/GetDataPersonasAllResponse")]
        System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona[]> GetDataPersonasAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataPersona", ReplyAction="http://tempuri.org/IServiceVentas/GetDataPersonaResponse")]
        SGV.Web.ServiceReferenceVentas.Persona GetDataPersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/GetDataPersona", ReplyAction="http://tempuri.org/IServiceVentas/GetDataPersonaResponse")]
        System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> GetDataPersonaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVentasChannel : SGV.Web.ServiceReferenceVentas.IServiceVentas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVentasClient : System.ServiceModel.ClientBase<SGV.Web.ServiceReferenceVentas.IServiceVentas>, SGV.Web.ServiceReferenceVentas.IServiceVentas {
        
        public ServiceVentasClient() {
        }
        
        public ServiceVentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGV.Web.ServiceReferenceVentas.Ciudad[] GetDataCiudadesAll() {
            return base.Channel.GetDataCiudadesAll();
        }
        
        public System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Ciudad[]> GetDataCiudadesAllAsync() {
            return base.Channel.GetDataCiudadesAllAsync();
        }
        
        public SGV.Web.ServiceReferenceVentas.Persona CreatePersona(SGV.Web.ServiceReferenceVentas.Persona persona) {
            return base.Channel.CreatePersona(persona);
        }
        
        public System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> CreatePersonaAsync(SGV.Web.ServiceReferenceVentas.Persona persona) {
            return base.Channel.CreatePersonaAsync(persona);
        }
        
        public SGV.Web.ServiceReferenceVentas.Persona UpdatePersona(SGV.Web.ServiceReferenceVentas.Persona persona) {
            return base.Channel.UpdatePersona(persona);
        }
        
        public System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> UpdatePersonaAsync(SGV.Web.ServiceReferenceVentas.Persona persona) {
            return base.Channel.UpdatePersonaAsync(persona);
        }
        
        public bool DeletePersona(int id) {
            return base.Channel.DeletePersona(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePersonaAsync(int id) {
            return base.Channel.DeletePersonaAsync(id);
        }
        
        public SGV.Web.ServiceReferenceVentas.Persona[] GetDataPersonasAll() {
            return base.Channel.GetDataPersonasAll();
        }
        
        public System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona[]> GetDataPersonasAllAsync() {
            return base.Channel.GetDataPersonasAllAsync();
        }
        
        public SGV.Web.ServiceReferenceVentas.Persona GetDataPersona(int id) {
            return base.Channel.GetDataPersona(id);
        }
        
        public System.Threading.Tasks.Task<SGV.Web.ServiceReferenceVentas.Persona> GetDataPersonaAsync(int id) {
            return base.Channel.GetDataPersonaAsync(id);
        }
    }
}
